### PR TITLE
Bump dependencies and release 2.0.0

### PR DESCRIPTION
**Pull request by conao3**
helm-swoop can't byte-compile with Emacs-24.3
```
In toplevel form:
helm-swoop.el:90:1:Error: Symbol's function definition is void: advice-add
make: *** [helm-swoop.elc] Error 1
```

### CODE REVIEW

**Comment by cireu** [comment]
Please be patient, I'd like to bump helm to 3.2 and release 2.0.0 with drop support of Emacs 24.3 together ;)

**Comment by conao3** [comment]
Yes, I agree with it.

**Comment by conao3** [comment]
Notice: I bump to version 2.0.0 in code but MELPA stable still distributes v1.7.4.
We `tag` this commit after more testing this version.

**Comment by conao3** [comment]
Do you think this PR needs discussion? In my opinion, the wrong version of helm is a bug, and I think it should be fixed as soon as possible.

In fact, this is what we got back to when you reverted all of your PR #145 when #148.
Create another PR if necessary, how do you think?

**Comment by cireu** [comment]
Can you help clean all byte-compiler warnings in helm-swoop.el? Just like https://github.com/emacsorphanage/helm-swoop/commit/7fcb4013da3bf956715ea19996b62be10ef9b386

And we can bump version to 2.0.0 after clean all warnings.

No need to a new branch, do it here is OK.

**Comment by conao3** [comment]
I Cherry-pick that commit.

**Comment by cireu** [comment]
I squash them and merge.

**Pull request merged**
