### PR TITLE
[fix] Rename `helm-update-hook` to `helm-after-update-hook`

### PR DESCRIPTION
**Pull request by cireu**
----

Something missed in #155.

### CODE REVIEW

**Comment by cireu** [comment]
Please tag 2.0.0 on this commit. @conao3

**Comment by conao3** [comment]
OK.
And I overlooked this too, I'm sorry.

**Comment by conao3** [comment]
[Offtopic]
I prefer to `normal merge` with merge commit instead of `squash and merge`.

The history of git should be recorded as closely as possible. And the history that seems to be pushed directly to the master is not good.
How do you think?

**Comment by cireu** [comment]
I agree with you.

**Comment by conao3** [comment]
Thanks!

**Pull request merged**
