### PR TITLE
Add git-hook script, Makefile, CONTRIBUTING.org

### PR DESCRIPTION
**Pull request by conao3**
This solves your suggestion in #152.
And add docker testing environment with Emacs-24.4 to Emacs 26.2.
(With writing this PR, I found this package does not work in Emacs-24.3.
This issue should also be solved.)

### CODE REVIEW

**Comment by cireu** [comment]
Why not use [Cask](https://github.com/cask/cask)? Cask can manage dependency automatically, and cask also support fetch library from github(for cort-test.el)

**Comment by conao3** [comment]
Cask is not required. Our only purpose is to fetch and unpack a few packages with `curl` and `tar`, for which the Cask is overspec.

But I'm interested in how much easier it is to use Cask. If you have time, please rewrite it. I have never used Cask and I have no intention of using it.

**Comment by conao3** [comment]
CC @rejeep (a member of cask)

A month has passed.
Anyway, we need a test environment. Even if you can't write enough test cases, it's better than just making sure you can compile without errors or warnings.
I want to run Emacs tests with multiple versions in Docker. We already have a Makefile for that, but if Cask simplifies that flow, I'll be interested in it.

Is it possible to simplify with Cask what I am requesting?

---
P.S.
If @rejeep have time, please tell us about multi-version testing at cask?
I currently have [dockerize Emacs](https://github.com/conao3/docker-emacs), but other solutions are possible if we are easy to prepare and provide a completely separate test environment.

**Comment by conao3** [comment]
Close because #170 merged.

**Pull request closed without merging**
