### PR TITLE
indent-buffer in helm-swoop.el

### PR DESCRIPTION
**Pull request by conao3**
Just do indent-buffer in helm-swoop.el

### CODE REVIEW

**Comment by cireu** [comment]
Good, would you like to write a indentation script for helm-swoop? we can add it to git hooks.

Personally I use `common-lisp-indent-function` because it can indent `cl-flet` to

```
(cl-flet ((a-simple-function ()
            (do-something-here)))
  ...)
```

but not
```
(cl-flet ((a-simple-function ()
                             (do-something-here)))
  ugly!)
```

If you can add such script will be helpful to keep the code consistency!

**Comment by conao3** [comment]
Good, but how automatically install git hook when anyone clones this repository?
I know, githook is completely local script. So this issue solve just you place some script in your local repository `.git` folder.

**Comment by cireu** [comment]
You can create a new folder `dev/git-hooks`, and put your script into it. And we add some instruction (e.g. CONTRIBUTION.org)

**Comment by conao3** [comment]
OK. I create it in another PR.

**Comment by conao3** [comment]
There are no issues, please merge it.
I want to create another branch after this merge commit.

**Pull request merged**
