### PR TITLE
License under GPLv3 instead of GPLv2

### PR DESCRIPTION
**Pull request by conao3**
CC @tarsius 

Update license to GPLv3 from GPLv2
This change may need discussion or/and release another version.

### CODE REVIEW

**Comment by tarsius** [comment]
> This change may need discussion or/and release another version.

We do not need the permission of past contributors because they have already granted it to us:

> [...] either version 2 of the License, or (at your option) any later version.

> or/and release another version.

I don't understand what you mean here. Another version of the license? (No other version would actually makes sense.) Or another *license* (not another *version/release of the license*). Or making another release of this package after bumping the version of the used license?

IMO GPLv3 "or (at your option) any later version" is the right way to go.

You accidentally put a copy of **AGPLv3** into the `LICENSE` file instead of **GPLv3** as intended.

**Comment by conao3** [comment]
Thanks, @tarsius. And I fix wrong LICENSE file immediately.

**Comment by cireu** [comment]
I'm OK with it. merge it when you think you're ready @conao3

**Comment by conao3** [comment]
OK. I'll merge after rebasing to master.

**Pull request merged**
