### PR TITLE
Quick fix to `helm-swoop`

### PR DESCRIPTION
**Pull request by cireu**
Close https://github.com/emacsorphanage/helm-swoop/issues/133 https://github.com/emacsorphanage/helm-swoop/issues/123 

Clean byte-compiler warnings 

Update dependency helm to 3.2

### CODE REVIEW

**Comment by cireu** [comment]
@JesusMtnez @conao3 Do you interested in review this PR?

**Comment by conao3** [comment]
OK.

Related to 881c535 I think this repository have maintained emacsorphanage for now.
It would be undesirable to write the name of an individual. We should be involved in this package as part of the organization.

I am not familiar with helm, so I say just looks good to me.

**Comment by cireu** [comment]
@conao3 I edit the copyright from my name to Emacsorphanage, but I'd like to keep the Maintainer line because Github orgnization doesn't seems to have a email address.

**Comment by conao3** [comment]
I think it is not desirable to keep the maintainer line.
In fact, the change is not directly related to this PR. You should first delete that line and discuss with @tarsius in another issue what we prefer to write about the maintainer line.

With at least four people (@tarsius, @cireu, @JesusMtnez, @conao3) expected to have maintenance authority, I don't agree with writing one maintainer line per one person to add nonessential information.

**Comment by cireu** [comment]
Ok, I remove the assignment commit until we draw the conclusion of https://github.com/melpa/melpa/issues/6347

**Pull request merged**
